/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_EXPERIMENTAL_AVERAGEOIS_ALL_HPP
#define QL_EXPERIMENTAL_AVERAGEOIS_ALL_HPP

#include <ql/experimental/averageois/averageoiscouponpricer.hpp>
#include <ql/experimental/averageois/arithmeticaverageois.hpp>
#include <ql/experimental/averageois/arithmeticoisratehelper.hpp>
#include <ql/experimental/averageois/makearithmeticaverageois.hpp>


#endif
