/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_PRICINGENGINES_CREDIT_ALL_HPP
#define QL_PRICINGENGINES_CREDIT_ALL_HPP

#include <ql/pricingengines/credit/integralcdsengine.hpp>
#include <ql/pricingengines/credit/isdacdsengine.hpp>
#include <ql/pricingengines/credit/midpointcdsengine.hpp>


#endif
