/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_MATH_ODE_ALL_HPP
#define QL_MATH_ODE_ALL_HPP

#include <ql/math/ode/adaptiverungekutta.hpp>


#endif
