/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_MODELS_VOLATILITY_ALL_HPP
#define QL_MODELS_VOLATILITY_ALL_HPP

#include <ql/models/volatility/constantestimator.hpp>
#include <ql/models/volatility/simplelocalestimator.hpp>
#include <ql/models/volatility/garmanklass.hpp>
#include <ql/models/volatility/garch.hpp>


#endif
