image:
  - Visual Studio 2015
  - Visual Studio 2019

platform: x64
configuration: Release

version: ci.{build}

build:
  parallel: true
  project: QuantLib.sln
  verbosity: normal

for:
-
  matrix:
    only:
      - image: Visual Studio 2015
  before_build:
    - COPY .appveyor\VS2015.props .\Build.props
-
  matrix:
    only:
      - image: Visual Studio 2019
  before_build:
    - COPY .appveyor\VS2019.props .\Build.props
    - COPY .appveyor\Unity.props .\Directory.Build.props

test_script:
  - .\test-suite\bin\QuantLib-test-suite-x64-mt.exe --log_level=message --build_info=yes -- --faster
