/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_METHODS_LATTICES_ALL_HPP
#define QL_METHODS_LATTICES_ALL_HPP

#include <ql/methods/lattices/binomialtree.hpp>
#include <ql/methods/lattices/bsmlattice.hpp>
#include <ql/methods/lattices/lattice.hpp>
#include <ql/methods/lattices/lattice1d.hpp>
#include <ql/methods/lattices/lattice2d.hpp>
#include <ql/methods/lattices/tree.hpp>
#include <ql/methods/lattices/trinomialtree.hpp>


#endif
