/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_MODELS_MARKETMODELS_BROWNIANGENERATORS_ALL_HPP
#define QL_MODELS_MARKETMODELS_BROWNIANGENERATORS_ALL_HPP

#include <ql/models/marketmodels/browniangenerators/mtbrowniangenerator.hpp>
#include <ql/models/marketmodels/browniangenerators/sobolbrowniangenerator.hpp>


#endif
