/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_PRICINGENGINES_QUANTO_ALL_HPP
#define QL_PRICINGENGINES_QUANTO_ALL_HPP

#include <ql/pricingengines/quanto/quantoengine.hpp>


#endif
