/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_MODELS_EQUITY_ALL_HPP
#define QL_MODELS_EQUITY_ALL_HPP

#include <ql/models/equity/batesmodel.hpp>
#include <ql/models/equity/gjrgarchmodel.hpp>
#include <ql/models/equity/hestonmodel.hpp>
#include <ql/models/equity/hestonmodelhelper.hpp>
#include <ql/models/equity/piecewisetimedependenthestonmodel.hpp>


#endif
