/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_EXPERIMENTAL_SHORTRATE_ALL_HPP
#define QL_EXPERIMENTAL_SHORTRATE_ALL_HPP

#include <ql/experimental/shortrate/generalizedhullwhite.hpp>
#include <ql/experimental/shortrate/generalizedornsteinuhlenbeckprocess.hpp>


#endif
