/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_EXPERIMENTAL_CATBONDS_ALL_HPP
#define QL_EXPERIMENTAL_CATBONDS_ALL_HPP

#include <ql/experimental/catbonds/catbond.hpp>
#include <ql/experimental/catbonds/catrisk.hpp>
#include <ql/experimental/catbonds/montecarlocatbondengine.hpp>
#include <ql/experimental/catbonds/riskynotional.hpp>


#endif
