/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_EXPERIMENTAL_AMORTIZINGBONDS_ALL_HPP
#define QL_EXPERIMENTAL_AMORTIZINGBONDS_ALL_HPP

#include <ql/experimental/amortizingbonds/amortizingcmsratebond.hpp>
#include <ql/experimental/amortizingbonds/amortizingfixedratebond.hpp>
#include <ql/experimental/amortizingbonds/amortizingfloatingratebond.hpp>


#endif
