/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_TERMSTRUCTURES_VOLATILITY_INFLATION_ALL_HPP
#define QL_TERMSTRUCTURES_VOLATILITY_INFLATION_ALL_HPP

#include <ql/termstructures/volatility/inflation/constantcpivolatility.hpp>
#include <ql/termstructures/volatility/inflation/cpivolatilitystructure.hpp>
#include <ql/termstructures/volatility/inflation/yoyinflationoptionletvolatilitystructure.hpp>


#endif
