/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_PATTERNS_ALL_HPP
#define QL_PATTERNS_ALL_HPP

#include <ql/patterns/composite.hpp>
#include <ql/patterns/curiouslyrecurring.hpp>
#include <ql/patterns/lazyobject.hpp>
#include <ql/patterns/observable.hpp>
#include <ql/patterns/singleton.hpp>
#include <ql/patterns/visitor.hpp>


#endif
