/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_LEGACY_ALL_HPP
#define QL_LEGACY_ALL_HPP

#include <ql/legacy/libormarketmodels/all.hpp>

#endif
