/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_MODELS_SHORTRATE_TWOFACTORMODELS_ALL_HPP
#define QL_MODELS_SHORTRATE_TWOFACTORMODELS_ALL_HPP

#include <ql/models/shortrate/twofactormodels/g2.hpp>


#endif
