/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifndef QL_EXPERIMENTAL_LATTICES_ALL_HPP
#define QL_EXPERIMENTAL_LATTICES_ALL_HPP

#include <ql/experimental/lattices/extendedbinomialtree.hpp>


#endif
